import {Scanner} from "./CScanner.ts";
import {Token, TokenType} from "./CTokens.ts";
import {ParserError} from "./CErrors.ts";

/**
 * CVIS Visualisation suite: Token Stream - Ben McIlveen
 * Used by the parser to manage the stream of tokens generated by the scanner.
 */

export class CTokenStream {
    private tokens: Token[];
    private current: number = 0;

    constructor(scanner: Scanner) {
        this.tokens = scanner.getAllTokens();
    }


    // Look ahead at the next token without consuming it
    peek = (offset: number = 0): Token => {
        const index = this.current + offset;
        if (index >= this.tokens.length) {
            return this.tokens[this.tokens.length - 1]; // Will hit eof
        }

        return this.tokens[index];
    }

    // Consume the next token and move the current index forward
    consume = (): Token => {
        if (this.isFinished()) {
            return this.tokens[this.tokens.length - 1]; // Will hit eof
        }
        return this.tokens[this.current++];

    }

    // Only consume the next token if it matches the expected type
    match = (type: TokenType): boolean => {
        if (this.isFinished())
            return false;
        if (this.peek().type !== type)
            return false;

        this.current++;
        return true;
    }

    // Move cursor back by a number of steps
    rewind = (steps: number) => {
        if (this.current - steps > 0)
            this.current -= steps;
        else
            this.current = 0;
    }

    // Only accept and consume if the next token matches the expected type, throw an error if it doesn't
    expect = (type: TokenType, message: string): Token => {
        const token = this.peek();
        if (token.type === type)
            return this.consume();

        throw new ParserError(message, token, type);

    }

    // Check if at then end of the stream
    isFinished = () => {
        return this.peek().type === TokenType.EOF; // will hit eof as above
    }


}